# Generated by Django 5.2.1 on 2025-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_user_details_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='profile_Picture',
            field=models.ImageField(default='null', upload_to='profile-picture/'),
        ),
    ]
