# Generated by Django 5.2.1 on 2025-06-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='user_profile',
            new_name='profile_Picture',
        ),
    ]
